import { DOMAINS } from '../data/rubric.js'

function formatDate() {
  return new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })
}

export function buildReportText({ intake, result, tier, answers, skippedOptional }) {
  const lines = []
  lines.push('DISTRICT AI GOVERNANCE READINESS ASSESSMENT')
  lines.push(`Generated ${formatDate()}`)
  lines.push('='.repeat(60))
  lines.push('')

  lines.push('DISTRICT SNAPSHOT')
  lines.push('-'.repeat(60))
  if (intake.districtName) lines.push(`District: ${intake.districtName}`)
  if (intake.role) lines.push(`Completed by (role): ${intake.role}`)
  if (intake.enrollment) lines.push(`Enrollment: ${intake.enrollment}`)
  if (intake.schoolCount) lines.push(`Schools: ${intake.schoolCount}`)
  if (intake.goals?.length) lines.push(`Goals for this assessment: ${intake.goals.join('; ')}`)
  if (intake.notes) lines.push(`Notes: ${intake.notes}`)
  lines.push('')

  lines.push('OVERALL SCORE')
  lines.push('-'.repeat(60))
  lines.push(`${result.totalEarned} / ${result.totalMax} points (${result.percent}%) — ${tier.label}`)
  lines.push(tier.description)
  lines.push(`${result.totalAnswered} of ${result.totalQuestions} questions answered${skippedOptional ? ' (Infrastructure & Cybersecurity skipped)' : ''}.`)
  lines.push('')

  lines.push('SCORE BY DOMAIN')
  lines.push('-'.repeat(60))
  result.byDomain.forEach((d) => {
    lines.push(`${d.title}: ${d.skipped ? 'skipped' : `${d.earnedPoints} / ${d.maxPoints}`}`)
  })
  lines.push('')

  lines.push('PRIORITY GAPS (questions scored "Not in place" or "Partially in place")')
  lines.push('-'.repeat(60))
  let gapCount = 0
  DOMAINS.forEach((domain) => {
    if (domain.optional && skippedOptional) return
    const gaps = domain.questions.filter((q) => {
      const score = answers[q.id]
      return typeof score === 'number' && score <= 1
    })
    if (gaps.length === 0) return
    lines.push(`\n${domain.title}:`)
    gaps.forEach((q) => {
      const score = answers[q.id]
      const level = q.levels.find((l) => l.score === score)
      lines.push(`  - [${level.label}] ${q.text}`)
      gapCount += 1
    })
  })
  if (gapCount === 0) {
    lines.push('No questions scored below "Mostly in place" — no priority gaps identified.')
  }
  lines.push('')

  lines.push('-'.repeat(60))
  lines.push('Generated by the District AI Governance Tutorial (ISSC698 capstone project).')
  lines.push('This report was created entirely in your browser; no data was transmitted or stored remotely.')

  return lines.join('\n')
}

export function downloadReport(text, filename) {
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
